// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuiwratkqezsiweocbpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1aXdyYXRrcWV6c2l3ZW9jYnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDc1NDksImV4cCI6MjA3NDM4MzU0OX0.uVPgikznUJ0OjeXvwmHvf9aT-2Ix8QI3RznASmuFz0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});